services:
  qdrant:
  image: qdrant/qdrant:v1.13.4
  restart: always
  container_name: qdrant
  ports:
    - 6333:6333
    - 6334:6334
  expose:
    - 6333
    - 6334
    - 6335
  volumes:
    - ./data:/qdrant/storage
    - ./certs:/certs
  environment:
    - QDRANT__SERVICE__API_KEY=sdlVp9fPBtj5ukN5hMYLBjaq5sw6QMhF
    - QDRANT__SERVICE__ENABLE_TLS=1
    - QDRANT__TLS__CERT=/certs/pc.com.pem
    - QDRANT__TLS__KEY=/certs/pc.com-key.pem